name: raa_tugas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Bluetooth Low Energy (BLE)
  flutter_blue_plus: ^1.35.5          # versi sudah terbaru

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.15          # update minor terbaru
  firebase_core: ^3.13.0               # update terbaru
  firebase_auth: ^5.5.3                # update terbaru
  cloud_firestore: ^5.6.7               # update terbaru
  async: ^2.12.0                      # update minor terbaru
  fake_async: ^1.3.2                  # update patch terbaru
  leak_tracker: ^10.0.8               # update minor terbaru
  vector_math: ^2.1.4                 # update minor terbaru
  material_color_utilities: ^0.11.1   # update minor terbaru
  audioplayers: ^6.4.0                # update terbaru
  provider: ^6.0.5                    # versi ini sudah cukup baru
  permission_handler: ^11.3.0          # update patch terbaru
  vibration: ^3.1.3                   # versi terbaru untuk fix error android embedding v2
  flutter_bluetooth_serial: ^0.4.0
  flutter_reactive_ble: ^5.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  
 

flutter:
  uses-material-design: true

  assets:
    - assets/mixkit_emergency_alert.mp3
