// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeQMcDDZQXujkLz7A4gfUlQSsDkXVnoXo',
    appId: '1:641291552138:web:921c8e0feb7700d8a27473',
    messagingSenderId: '641291552138',
    projectId: 'tugasta-618a1',
    authDomain: 'tugasta-618a1.firebaseapp.com',
    storageBucket: 'tugasta-618a1.appspot.com', // Pastikan URL storage sesuai dengan di Firebase Console
    measurementId: 'G-FM44VLC7DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmIWn30dmftySlPX44YX_fXdg85X-YwrM',
    appId: '1:641291552138:android:83a3230072afa2fba27473',
    messagingSenderId: '641291552138',
    projectId: 'tugasta-618a1',
    storageBucket: 'tugasta-618a1.appspot.com', // Sesuaikan dengan yang ada di Firebase Console
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK5QNXLE9_G3pUOn4Z36fJm4Om_F5vsjM',
    appId: '1:641291552138:ios:02caa71fa0822024a27473',
    messagingSenderId: '641291552138',
    projectId: 'tugasta-618a1',
    storageBucket: 'tugasta-618a1.appspot.com',
    iosBundleId: 'com.example.raaTugas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK5QNXLE9_G3pUOn4Z36fJm4Om_F5vsjM',
    appId: '1:641291552138:ios:02caa71fa0822024a27473',
    messagingSenderId: '641291552138',
    projectId: 'tugasta-618a1',
    storageBucket: 'tugasta-618a1.appspot.com',
    iosBundleId: 'com.example.raaTugas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeQMcDDZQXujkLz7A4gfUlQSsDkXVnoXo',
    appId: '1:641291552138:web:0cd027a7c1c3ae0da27473',
    messagingSenderId: '641291552138',
    projectId: 'tugasta-618a1',
    authDomain: 'tugasta-618a1.firebaseapp.com',
    storageBucket: 'tugasta-618a1.appspot.com',
    measurementId: 'G-5MP58DETHT',
  );
}
